id = 7
class = "sound_set_7"
name = "Furni Sounds Vol. 1"
description = "Sound effects for Furni"
masterclass = "SFX"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_7_icon.png"
mainColor = "#FFCC33"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/Furni_Sounds_1.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
