id = 9
class = "sound_set_9"
name = "Mysto Magica"
description = "Mystical ambient soundscapes"
masterclass = "Electro"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_9_icon.png"
mainColor = "#880000"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/Mysto_Magica.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
