id = 21
class = "sound_set_21"
name = "Snotty Day"
description = "Headbanging riffs"
masterclass = "Heavy"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_21_icon.png"
mainColor = "#444444"
caseColor = "#666666"
preview = "https://images.habbo.com/c_images/album2348/Snotty_Day.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
