id = 26
class = "sound_set_26"
name = "Bhangra Mangra"
description = "Indian rhythms"
masterclass = "Latin"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_26_icon.png"
mainColor = "#CC33CC"
caseColor = "#CC6666"
preview = "https://images.habbo.com/c_images/album2348/Bhangra_Mangra.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
