id = 18
class = "sound_set_18"
name = "Little Tanga Beach"
description = "The Brazilian rhythms as above"
masterclass = "Latin"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_18_icon.png"
mainColor = "#66CC00"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/Little_Tanga_Beach.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
