id = 10
class = "sound_set_10"
name = "Boy Band"
description = "Cute boys crooning tunes"
masterclass = "Bling"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_10_icon.png"
mainColor = "#555555"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/Boy_Band_Sensation.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
