id = 3
class = "sound_set_3"
name = "BattleBall Theme"
description = "8bit music madness"
masterclass = "Electro"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_3_icon.png"
mainColor = "#FF6666"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/BattleBall_Theme.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
