id = 5
class = "sound_set_5"
name = "Dark Skies"
description = "The dark side of Habbo"
masterclass = "SFX"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_5_icon.png"
mainColor = "#444444"
caseColor = "#777777"
preview = "https://images.habbo.com/c_images/album2348/Dark_Skies.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
