id = 6
class = "sound_set_6"
name = "Ambience"
description = "Background ambient loops"
masterclass = "Ambient"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_6_icon.png"
mainColor = "#BBBBBB"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/Ambiences.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
