id = 1
class = "sound_set_1"
name = "Duck Funk"
description = "Get your party started!"
masterclass = "Electro"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_1_icon.png"
mainColor = "#CC9900"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/Duck_Funk_preview.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
