id = 19
class = "sound_set_19"
name = "MnM"
description = "Fan and Funky"
masterclass = "SFX"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_19_icon.png"
mainColor = "#6699FF"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/MnM.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
