id = 22
class = "sound_set_22"
name = "A Day In The Park"
description = "Nature sound effects"
masterclass = "Ambient"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_22_icon.png"
mainColor = "#66CCFF"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/A_Day_In_The_Park.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
