id = 13
class = "sound_set_13"
name = "Cafe Muzzakh"
description = "For that special elevator"
masterclass = "Latin"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_13_icon.png"
mainColor = "#CCCC66"
caseColor = "#669933"
preview = "https://images.habbo.com/c_images/album2348/Cafe_Muzzakh.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
