id = 24
class = "sound_set_24"
name = "Compu FX"
description = "Sci-Fi sound effects"
masterclass = "SFX"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_24_icon.png"
mainColor = "#333333"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/Compu_FX.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
