id = 11
class = "sound_set_11"
name = "Spicey Donna"
description = "D.I.S.C.O. grooves"
masterclass = "Disco"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_11_icon.png"
mainColor = "#996633"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/Spicey_Donna.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
