id = 12
class = "sound_set_12"
name = "Abe Normal"
description = "Weirdness for the open minded"
masterclass = "8-bit"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_12_icon.png"
mainColor = "#CC6633"
caseColor = "#339933"
preview = "https://images.habbo.com/c_images/album2348/Abe_Normal.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
