id = 2
class = "sound_set_2"
name = "DJ Fuse's Habbo Theme"
description = "A collection of rocking party sounds"
masterclass = "Electro"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_2_icon.png"
mainColor = "#66CC99"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/Habbo_Theme.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
