id = 25
class = "sound_set_25"
name = "Parteh Pack"
description = "Happy and jolly party sounds"
masterclass = "SFX"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_25_icon.png"
mainColor = "#FFCC66"
caseColor = "#CC6666"
preview = "https://images.habbo.com/c_images/album2348/Party_Pack.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
