id = 15
class = "sound_set_15"
name = "El Generico"
description = "R'n'B massivo"
masterclass = "Disco"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_15_icon.png"
mainColor = "#666633"
caseColor = "#CC9900"
preview = "https://images.habbo.com/c_images/album2348/El_Generico.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
