id = 8
class = "sound_set_8"
name = "Electronica"
description = "Mellow electric grooves"
masterclass = "Electro"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_8_icon.png"
mainColor = "#FF99FF"
caseColor = "#BBBBBB"
preview = "https://images.habbo.com/c_images/album2348/Electronica.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
