id = 23
class = "sound_set_23"
name = "Nature Nightlight"
description = "Can you cricket? Owling good sound effects"
masterclass = "Ambient"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_23_icon.png"
mainColor = "#666666"
caseColor = "#336699"
preview = "https://images.habbo.com/c_images/album2348/Nature_Nightlife.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
