id = 4
class = "sound_set_4"
name = "Sunset Adventures"
description = "For chilling moments"
masterclass = "Latin"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_4_icon.png"
mainColor = "#6699CC"
caseColor = "#999999"
preview = "https://images.habbo.com/c_images/album2348/Sunset_Adventures.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
