id = 17
class = "sound_set_17"
name = "Jive Sideburns"
description = "Funky disco loops"
masterclass = "Disco"
image = "https://images.habbo.com/dcr/hof_furni/45508/sound_set_17_icon.png"
mainColor = "#FF3333"
caseColor = "#CC9900"
preview = "https://images.habbo.com/c_images/album2348/Jive_Sideburns.mp3"

[releaseDate]
hhfi = "08/03/2007"
hhus = "20/06/2007"
hhbr = "15/06/2007"
hhous = "04/11/2024"
hhoes = "04/11/2024"
hhobr = "04/11/2024"
